### ISSUE TITLE
[TS Error]: AngularJS + Typescript 2.5.2 + Swagger TS code generation error while importing

### ISSUE THREAD

**Issue by Morkos** [mtennoe/swagger-typescript-codegen#71]
##### Description
Hi there,

I filed the same bug here: https://github.com/swagger-api/swagger-codegen/issues/9328
but I am facing a different set of issues with this swagger codegen version.

The following errors happen when I try to compile the generated TS client file. 

dist/otrBackendService.ts(80,16): error TS1127: Invalid character.
dist/otrBackendService.ts(80,32): error TS1127: Invalid character.
dist/otrBackendService.ts(80,34): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(81,9): error TS1005: ',' expected.
dist/otrBackendService.ts(81,18): error TS1005: ';' expected.
dist/otrBackendService.ts(136,20): error TS1127: Invalid character.
dist/otrBackendService.ts(136,36): error TS1127: Invalid character.
dist/otrBackendService.ts(136,38): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(137,9): error TS1005: ',' expected.
dist/otrBackendService.ts(137,18): error TS1005: ';' expected.
dist/otrBackendService.ts(618,16): error TS1127: Invalid character.
dist/otrBackendService.ts(618,36): error TS1127: Invalid character.
dist/otrBackendService.ts(618,55): error TS1127: Invalid character.
dist/otrBackendService.ts(618,56): error TS1127: Invalid character.
dist/otrBackendService.ts(618,58): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(619,9): error TS1005: ',' expected.
dist/otrBackendService.ts(619,18): error TS1005: ';' expected.
dist/otrBackendService.ts(1109,16): error TS1127: Invalid character.
dist/otrBackendService.ts(1109,32): error TS1127: Invalid character.
dist/otrBackendService.ts(1109,34): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(1110,9): error TS1005: ',' expected.
dist/otrBackendService.ts(1110,18): error TS1005: ';' expected.
dist/otrBackendService.ts(1128,34): error TS1127: Invalid character.
dist/otrBackendService.ts(1128,36): error TS1131: Property or signature expected.
dist/otrBackendService.ts(1128,53): error TS1127: Invalid character.
dist/otrBackendService.ts(1129,5): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(1130,26): error TS1109: Expression expected.
dist/otrBackendService.ts(1131,1): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(1162,20): error TS1127: Invalid character.
dist/otrBackendService.ts(1162,36): error TS1127: Invalid character.
dist/otrBackendService.ts(1162,38): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(1163,9): error TS1005: ',' expected.
dist/otrBackendService.ts(1163,18): error TS1005: ';' expected.
dist/otrBackendService.ts(1339,16): error TS1127: Invalid character.
dist/otrBackendService.ts(1339,29): error TS1127: Invalid character.
dist/otrBackendService.ts(1339,31): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(1340,9): error TS1005: ',' expected.
dist/otrBackendService.ts(1340,18): error TS1005: ';' expected.
dist/otrBackendService.ts(1653,32): error TS1127: Invalid character.
dist/otrBackendService.ts(1654,5): error TS1131: Property or signature expected.
dist/otrBackendService.ts(1654,11): error TS1127: Invalid character.
dist/otrBackendService.ts(1654,13): error TS1109: Expression expected.
dist/otrBackendService.ts(1655,5): error TS1109: Expression expected.
dist/otrBackendService.ts(1656,1): error TS1128: Declaration or statement expected.
dist/otrBackendService.ts(1865,23): error TS1127: Invalid character.
dist/otrBackendService.ts(1865,42): error TS1127: Invalid character.
dist/otrBackendService.ts(1865,44): error TS1128: Declaration or statement expected

##### Swagger-codegen version

1.9.5

##### Swagger declaration file content or url

Swagger JSON file used to generate TS client code. The JSON file should be fine.
https://otr-backend-service-us-devo.offtherecord.com/v2/api-docs 

##### gulp task used for generation

....
gulp.task('angular-codegen', function(done){

    var CodeGen = require('swagger-typescript-codegen').CodeGen;
    var dest = 'dist';
    apis.forEach(function(api){
        var swagger = JSON.parse(fs.readFileSync(api.swagger, 'utf-8'));
        var source = CodeGen.getTypescriptCode({ moduleName: api.moduleName, className: api.className, swagger: swagger });
        gutil.log('Generated ' + api.moduleName + '.js from ' + api.swagger);

        var generatedApiFile = dest + '/' + api.moduleName + '.ts';
        fs.writeFileSync(generatedApiFile, source, 'UTF-8');

        gulp.src([generatedApiFile]) //otherSources])
            .pipe(gulp.dest(dest))
            .pipe(notify("File has been successfully generated!"));
    });
    done();
});

##### Steps to reproduce

tsc --project .tsconfig

##### TSC Version

tsc --version
Version 2.5.2

##### .tsconfig file

{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "es5",
    "experimentalDecorators": true
  },
  "include": [
    "./public/app/"
  ]
}

#####  Question

Is there a version of TS that supports compilation of this files because perhaps the swagger codegen was generating TS code that was compliant against certain versions of the TS compiler? If not, how do we solve this?

**Comment by mtennoe** [comment]
Can you show an example of the code it is complaining about? We don't have any set requirements for TS versions, but 2.5.2 is fairly old - would it be possible to upgrade to a newer version? 3.4 (patched to 3.4.1) was recently released.

If that is not possible, it should be possible to take the current mustache templates and modify them to work with TS 2.5.2, then use those as custom templates

**Comment by Morkos** [comment]
Hi Maurice,

Yes, I upgraded to TS 3.3 to try it out, but still no cigar. New errors are here [1] and code is here [2].

[1]: https://gist.github.com/Morkos/474bef564b63a2e047b34a52b6bf13e7
[2]: https://gist.github.com/Morkos/71762f07b20210050527a87ee223ed95

Best,

**Comment by mtennoe** [comment]
Can you show a snippet of the output code it complains about?

**Comment by Morkos** [comment]
Hi Maurice,

I have links above, but not sure why github got rid of my footers to the links "1" and "2" above.

TS Generated Code: https://gist.github.com/Morkos/71762f07b20210050527a87ee223ed95
Compilation Errors: https://gist.github.com/Morkos/474bef564b63a2e047b34a52b6bf13e7

**Comment by mtennoe** [comment]
Looks like the errors are caused by the generator outputting `«` and `»` instead of `<` and `>` for use in the generic types. These characters don't exist in the codegenerator, so seems like they are coming from somewhere outside. Do you see these characters in the input swagger.json file?

**Comment by michalzaq12** [comment]
Some swagger spec generators (e.g Springfox Swagger2) outputting `«` and `»` instead of `<` and `>` in model definitions section 

Source code: [https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/DefaultGenericTypeNamingStrategy.java](url)

**Comment by Morkos** [comment]
Thank you both.

Hello @michalzaq12, is there a way to override this behavior? And yes I'm using Springfox Swagger2 (2.2.2). Is there an alternative?

**Comment by michalzaq12** [comment]
I do not know if it is the perfect solution, but it should work: 

`const swagger = JSON.parse(fs.readFileSync(file, 'UTF-8').replace('«', '<').replace('»', '>'));`

**Comment by mtennoe** [comment]
@Morkos - Closing this as its not related to the code generator itself. Please reopen if you disagree or want to reopen the discussion
